apiVersion : apps/v1
kind: Deployment
metadata:
  name: "scorestestapp"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: "scorestestapp"
  template:
    metadata:
      labels:
        app: "scorestestapp"
    spec:
      containers:
        - name: "scorestestapp"
          image: "scorestestapp.azurecr.io/365scorestest"
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi        
          ports:
          - containerPort: 80
          livenessProbe:
            httpGet:
              path: /liveness
              port: 80
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /hc
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 7
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "dev"            
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scorestestapp
spec:
  maxReplicas: 5 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scorestestapp
  targetCPUUtilizationPercentage: 66 # target CPU utilization
---