apiVersion: v1
kind: Service
metadata:
    name: "365scorestest-0f70"
    labels:
        app: "365scorestest-0f70"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "365scorestest-0f70"